### ISSUE TITLE
Can we experiment RGDAN on PEMS04 dataset?

### ISSUE THREAD

**Issue by sugar-hub** [wengwenchao123/RGDAN#3]
Dear Weng,

I notice that RGDAN is experimented on METRLA and PEMSBAY where the SE file in both datasets is needed during the training. Then an idea comes to me: can we experiment RGDAN on other dataset like PEMS04? Such dataset does not contain SE file.

Best wishes!

**Comment by wengwenchao123** [comment]
Of course. In fact, the SE file is generated using a predefined adjacency matrix (adj), and this is also applicable to PEMS04 and PEMS08. The relevant generation code is located in the node2vec folder. However, at that time, I converted the adj into a triplet format for storage and then used the networkx library to read and process the adj. I can't remember if directly reading the adj file would work, so it might be necessary to first convert the adj for PEMS04 and PEMS08 into the format of data/Adj(METR).txt before it can be used. Please try this first, and if there are any issues, we can continue the discussion.

**Comment by sugar-hub** [comment]
OK. Thank you! Let me have a try these days.

**Comment by sugar-hub** [comment]
Hi， author！

When I attempted to experiment on the PEMS04 dataset, the biggest issue I encountered was that the PEMS04 dataset has a dimensionality of 3, while the METRLA dataset has a dimensionality of 2. How should I handle the additional dimension?

**Comment by wengwenchao123** [comment]
This depends on the task at hand. The PEMS04 dataset includes three features: speed, flow, and occupancy. If you want to predict flow, you should input the flow feature. The METR-LA dataset includes a time dimension, which is manually constructed. You can construct a similar time dimension for the PEMS04 dataset, or you can choose to not use this dimension initially.

**Comment by sugar-hub** [comment]
I see that dataloader returns X, TE, and Y in train, val, and test. What do they mean?

**Comment by wengwenchao123** [comment]
X represents the historical data input, where TE denotes the time embedding used to represent time information corresponding to the time step section in my model graph, and Y represents the data to be predicted.

**Comment by wengwenchao123** [comment]
If you want to use TE on pems04, you need to first construct a time axis. However, pems04 does not have relevant content for this purpose. If you want to build a time axis similar to METR-LA, you can refer to the time axis construction method in the dataloader of DDGCRN. That method can also be used to construct the time axis for METR-LA.

**Comment by sugar-hub** [comment]
Thank you very much! Let me have more try in these days.
